export interface Guide {
  slug: string;
  title: string;
  description: string;
  kicker: string;
  /** Months (0–11) when the guide is most relevant — used to feature seasonal guides first. */
  months?: number[];
}

export const GUIDES: Guide[] = [
  { slug: 'hurricane-season', title: 'Hurricane Season Guide: Caribbean, Florida & Mexico', description: 'When hurricane season runs, which months carry the most risk, and the safest places to go in the Caribbean, Florida and Mexico.', kicker: 'Seasonal guide', months: [5, 6, 7, 8, 9, 10] },
  { slug: 'monsoon-season-asia', title: 'Monsoon Season in Asia: Where It Rains and When', description: 'Month-by-month monsoon guide for Thailand, Vietnam, Bali, India, Sri Lanka and more — and where stays dry instead.', kicker: 'Seasonal guide', months: [4, 5, 6, 7, 8, 9] },
  { slug: 'cherry-blossom-season', title: 'Cherry Blossom Season 2027: When and Where to See It', description: 'When cherry blossoms bloom in Tokyo, Kyoto, Okinawa, Hokkaido, Seoul, Washington, D.C. and beyond, and how to plan around the crowds.', kicker: 'Nature calendar', months: [0, 1, 2, 3] },
  { slug: 'northern-lights', title: 'Best Time to See the Northern Lights', description: 'When and where to see the aurora borealis — Iceland, Tromsø, Alaska and Canada — plus tips for better odds.', kicker: 'Nature calendar', months: [8, 9, 10, 11, 0, 1, 2] },
  { slug: 'winter-sun', title: 'Winter Sun: The Warmest Places to Go from December to February', description: 'Where to find reliable sunshine and warmth in winter, from the Caribbean and Canary Islands to Southeast Asia — ranked with real climate data.', kicker: 'Where to go', months: [9, 10, 11, 0, 1] },
  { slug: 'festival-calendar', title: 'Festival Calendar: The World’s Best Festivals Month by Month', description: 'A month-by-month calendar of famous festivals and seasonal events across our destinations — from Carnival to cherry blossoms.', kicker: 'Events' },
  { slug: 'cheapest-places-to-travel', title: 'The Cheapest Places to Travel (and When to Go)', description: 'Daily travel budgets for every destination we cover, sorted from cheapest — with the best-weather months for each.', kicker: 'Budget' },
  { slug: 'christmas-markets-europe', title: 'The Best Christmas Markets in Europe: Dates, Weather & Tips', description: 'When Europe’s favourite Christmas markets open — Vienna, Strasbourg, Prague, Nuremberg, Budapest and more — with December weather and planning tips.', kicker: 'Events', months: [9, 10, 11] },
  { slug: 'new-years-eve', title: 'Where to Spend New Year’s Eve: The World’s Best Celebrations', description: 'Fireworks over Sydney Harbour, Hogmanay in Edinburgh, Réveillon in Rio and more — the best places to see in the new year, with the weather to expect.', kicker: 'Events', months: [9, 10, 11] },
  { slug: 'ski-season', title: 'Ski Season Guide: When to Ski the Alps, Rockies, Japan and New Zealand', description: 'When ski seasons open and close around the world, when the snow is best, and where you can ski in every month of the year.', kicker: 'Seasonal guide', months: [8, 9, 10, 11, 0, 1, 2] },
  { slug: 'fall-foliage', title: 'Fall Foliage Guide: When and Where to See Autumn Colours', description: 'Peak autumn-leaf dates for New England, Quebec, the Smoky Mountains, Colorado, Japan, Korea and Europe — plus the southern-hemisphere autumn.', kicker: 'Nature calendar', months: [7, 8, 9, 10] },
  { slug: 'safari-season', title: 'Safari Season: The Best Time for an African Safari, Month by Month', description: 'When to see the Great Migration in Kenya and Tanzania, and the best months for Kruger, the Okavango Delta and Namibia’s Etosha.', kicker: 'Nature calendar' },
  { slug: 'whale-watching', title: 'Whale-Watching Calendar: Where to See Whales Every Month', description: 'Humpbacks in Hawaii and Mexico, orcas in Norway, blue whales in Sri Lanka and the Azores — the best whale-watching seasons worldwide.', kicker: 'Nature calendar' },
  { slug: 'machu-picchu', title: 'Best Time to Visit Machu Picchu: Weather, Crowds and Permits', description: 'Dry season vs rainy season at Machu Picchu, the Inca Trail’s February closure, daily visitor limits and how to book tickets.', kicker: 'Where to go' },
  { slug: 'galapagos-month-by-month', title: 'Galápagos Month by Month: Wildlife and Weather Calendar', description: 'What you’ll see in the Galápagos each month — nesting albatrosses, blue-footed booby courtship, sea lion pups — and warm vs cool seasons.', kicker: 'Nature calendar' },
  { slug: 'diving-snorkelling-seasons', title: 'Diving and Snorkelling Seasons Worldwide', description: 'The best months to dive or snorkel the Great Barrier Reef, the Maldives, the Red Sea, Komodo, Cozumel, Belize, the Galápagos and more.', kicker: 'Nature calendar' },
  { slug: 'sargassum-season', title: 'Sargassum Seaweed Season: Caribbean and Mexico Guide', description: 'When sargassum seaweed hits the beaches of Cancún, Tulum, Punta Cana and the Caribbean — and where to go to avoid it.', kicker: 'Seasonal guide', months: [2, 3, 4, 5, 6, 7, 8] },
  { slug: 'typhoon-season', title: 'Typhoon Season in Asia: Japan, Taiwan, the Philippines and Hong Kong', description: 'When typhoon season peaks in East and Southeast Asia, how it affects travel, and where to go instead.', kicker: 'Seasonal guide', months: [5, 6, 7, 8, 9] },
  { slug: 'disney-world', title: 'Best Time to Visit Disney World: Crowds, Weather and Prices', description: 'The quietest and busiest weeks at Walt Disney World, Orlando’s weather month by month, hurricane season and seasonal events.', kicker: 'Where to go' },
  { slug: 'spring-break', title: 'Spring Break Destinations by Budget', description: 'Where the weather is warm in March and April — from cheap Mexico and Central America to the Caribbean and Hawaii — with daily budgets.', kicker: 'Where to go', months: [0, 1, 2, 3] },
  { slug: 'honeymoon-destinations', title: 'Honeymoon Destinations by Month: Where to Go for Perfect Weather', description: 'The best romantic destinations for every month of the year, ranked by real weather data — islands, beaches and dreamy cities.', kicker: 'Where to go' },
  { slug: 'family-holidays', title: 'Family Holidays by Month: Where to Go in the School Holidays', description: 'Family-friendly destinations with great weather in every school holiday, from February half-term and spring break to summer and Christmas.', kicker: 'Where to go' },
  { slug: 'ramadan-travel', title: 'Travelling During Ramadan: What to Know (Ramadan 2027 Dates)', description: 'When Ramadan falls in 2027, what changes for visitors in Morocco, Egypt, Jordan, the UAE, Oman and Indonesia — and the upsides of going.', kicker: 'Practical', months: [10, 11, 0, 1, 2] },
  { slug: 'golden-week-japan', title: 'Golden Week in Japan: Dates and How to Travel Around It', description: 'When Japan’s Golden Week holidays fall, why trains and hotels sell out, and how to plan a spring trip around the crowds.', kicker: 'Practical', months: [1, 2, 3, 4] },
  { slug: 'travel-insurance', title: 'Travel Insurance Explained: What It Covers and What to Look For', description: 'A plain-English guide to travel insurance — medical cover, cancellations, hurricanes, adventure sports and the small print to check.', kicker: 'Practical' },
  { slug: 'esim-travel', title: 'eSIMs for Travel: How They Work and How to Choose One', description: 'How a travel eSIM works, which phones support it, how much data you need and how to set it up before you fly.', kicker: 'Practical' },
  { slug: 'packing-list', title: 'Packing List by Climate: Tropical, Desert, Cold and Mountain Trips', description: 'What to pack for every kind of weather — tropical beaches, monsoon rain, desert heat, winter cities and high altitude.', kicker: 'Practical' },
  { slug: 'shoulder-season', title: 'Shoulder Season: The Best-Value Months to Travel', description: 'Why spring and autumn shoulder seasons offer the best mix of weather, prices and crowds — with the best shoulder months for each region.', kicker: 'Budget' },
  { slug: 'iceland-ring-road', title: 'Iceland Ring Road: When to Drive It (and When Roads Close)', description: 'Driving Iceland’s Ring Road by season — daylight, weather, winter road closures and when the highland F-roads open.', kicker: 'Where to go' },
  { slug: 'japan-rainy-season', title: 'Japan Rainy Season (Tsuyu): When It Starts and Where to Go', description: 'When the rainy season starts and ends in Okinawa, Tokyo, Kyoto and Osaka, how wet it really gets, and why Hokkaido escapes it.', kicker: 'Seasonal guide', months: [3, 4, 5, 6] },
  { slug: 'bali-wet-season', title: 'Bali in the Wet Season: Is It Worth Going?', description: 'How rainy Bali really is from November to March, what the wet season is like day to day, and the upsides of going.', kicker: 'Seasonal guide', months: [9, 10, 11, 0, 1, 2] },
  { slug: 'india-monsoon', title: 'India’s Monsoon: When It Arrives and Where to Go Instead', description: 'How the monsoon sweeps across India from June to September — and the best places to go in India and nearby during the rains.', kicker: 'Seasonal guide', months: [3, 4, 5, 6, 7, 8] },
  { slug: 'midnight-sun', title: 'Midnight Sun: Where and When to See the Sun at Midnight', description: 'Where the sun doesn’t set in summer — Norway, Finland, Iceland, Alaska — with the dates and daylight hours for each destination.', kicker: 'Nature calendar', months: [3, 4, 5, 6] },
  { slug: 'great-barrier-reef', title: 'Best Time to Visit the Great Barrier Reef', description: 'Dry season vs stinger season, water temperature and visibility, and when to see whales, turtles and coral spawning on the reef.', kicker: 'Where to go' },
  { slug: 'hawaii-islands-compared', title: 'Hawaii Islands Compared: Which Island When?', description: 'Oahu, Maui, Kauai or the Big Island? How the weather, rain and whale season compare month by month — and which island suits you.', kicker: 'Compare' },
  { slug: 'caribbean-islands-compared', title: 'Caribbean Islands Compared by Season', description: 'Which Caribbean island has the best weather each month — from Aruba and Curaçao in hurricane season to Barbados, St Lucia and the Bahamas in winter.', kicker: 'Compare' },
  { slug: 'daylight-hours', title: 'Daylight Hours Around the World, Month by Month', description: 'How many hours of daylight to expect in every destination we cover, from the polar night in Tromsø to equatorial Singapore.', kicker: 'Practical' },
  { slug: 'best-time-to-visit-europe', title: 'Best Time to Visit Europe: A Month-by-Month Guide', description: 'The best months for Europe by region, with our top-rated destinations for every month, crowds, prices and the sweet-spot shoulder seasons.', kicker: 'Where to go' },
  { slug: 'thailand-islands-andaman-vs-gulf', title: 'Thailand Islands: Andaman Coast vs Gulf of Thailand by Season', description: 'Phuket and Krabi or Koh Samui, Koh Phangan and Koh Tao? Which side of Thailand has the better beach weather in every month.', kicker: 'Seasonal guide', months: [4, 5, 6, 7, 8, 9, 10] },
  { slug: 'costa-rica-green-season', title: 'Costa Rica Green Season: Is It Worth It?', description: 'What Costa Rica’s rainy season from May to November is really like, region by region and month by month — and when the Caribbean coast is driest.', kicker: 'Seasonal guide', months: [3, 4, 5, 6, 7, 8, 9] },
  { slug: 'cheapest-months-to-fly-to-europe', title: 'Cheapest Months to Fly to Europe from the US', description: 'When transatlantic fares are lowest, where the weather is best in those months, and practical ways to pay less for flights to Europe.', kicker: 'Budget', months: [8, 9, 10, 11, 0] },
  { slug: 'wildflower-seasons', title: 'Wildflower Seasons: Deserts, Alps and Namaqualand', description: 'When and where to see desert superblooms, tulips, lavender, alpine meadows and the spring flowers of Namaqualand and Western Australia.', kicker: 'Nature calendar', months: [0, 1, 2, 3, 4, 5, 6, 7] },
  { slug: 'carnival-season', title: 'Carnival Season 2027: Rio, Venice, Trinidad and New Orleans', description: 'Carnival 2027 dates for Rio, Salvador, Venice, Mardi Gras in New Orleans, Trinidad, the Canary Islands and Basel — with the February weather.', kicker: 'Events', months: [9, 10, 11, 0, 1] },
  { slug: 'where-to-go-for-easter', title: 'Where to Go for Easter 2027: Processions, Festivals and Spring Sun', description: 'Easter 2027 falls on 28 March. The best places for Holy Week traditions, from Seville to Antigua, and the warmest destinations for an Easter break.', kicker: 'Events', months: [0, 1, 2, 3] },
  { slug: 'stargazing-dark-skies', title: 'Best Places for Stargazing and Dark Skies', description: 'The world’s best places to see the Milky Way — the Atacama, Namibia, Mauna Kea, Tenerife, Uluru and US dark-sky parks — and when skies are clearest.', kicker: 'Nature calendar' },
  { slug: 'rainy-season-mexico-central-america', title: 'Rainy Season in Mexico and Central America', description: 'When the rainy season starts and ends in Cancún, Puerto Vallarta, Mexico City, Belize, Guatemala, Costa Rica and Panama — and where stays dry.', kicker: 'Seasonal guide', months: [4, 5, 6, 7, 8, 9] },
  { slug: 'road-trips-by-season', title: 'Best Road Trips by Season', description: 'The world’s great drives at their best: Utah and Andalusia in spring, Iceland and the fjords in summer, New England in autumn, Australia in winter.', kicker: 'Where to go' },
  { slug: 'solo-travel-by-month', title: 'Solo Travel: Safe, Sunny Places by Month', description: 'Easy, well-travelled destinations for travelling alone, ranked by weather for every month — plus practical tips for solo trips.', kicker: 'Where to go' },
  { slug: 'halloween-dia-de-muertos', title: 'Where to Celebrate Halloween and Día de los Muertos', description: 'The best places for Halloween — New York, New Orleans, Orlando, Ireland — and for Mexico’s Day of the Dead in Oaxaca, Mexico City and beyond.', kicker: 'Events', months: [8, 9] },
];

export const guideUrl = (slug: string) => `/guides/${slug}/`;

/** Guides relevant now first (by month), then the rest — for "featured guides" lists. */
export function seasonalGuides(month: number): Guide[] {
  const now = GUIDES.filter((g) => g.months?.includes(month));
  return [...now, ...GUIDES.filter((g) => !now.includes(g))];
}
